server {
    listen 8080;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    # Sirve ficheros tal cual, y que 404 responda con 404.html si existe
    location / {
        try_files $uri $uri/ /404.html =404;
    }
}
