name: Deployment alejandroguerra.es Docker Image
on:
  push:
    branches:
      - develop

jobs:
  Build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'pro' || github.ref == 'refs/heads/develop' && 'dev'}}
    permissions:
      contents: read
      id-token: write

    steps:
    - id: auth
      uses: google-github-actions/auth@v1
      with:
        workload_identity_provider: "projects/1069825445841/locations/global/workloadIdentityPools/gwi-alejandroguerra-github-cicd/providers/gwi-aleguerra-ghb-cicd-provdr"
        service_account: "github-cicd-deployer@alejandro-guerra-es.iam.gserviceaccount.com"

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ vars.GCP_PROJECT_ID }}

    - name: Sanity check token
      run: |
        echo "ADC: $GOOGLE_APPLICATION_CREDENTIALS"
        gcloud auth print-access-token >/dev/null
        echo "Token OK"
